// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP2XHvCm5hnoD2jE9NuxOLHaDppOV_4mo',
    appId: '1:287249177433:web:53f300af3c7763ef5cca48',
    messagingSenderId: '287249177433',
    projectId: 'myapp-9f915',
    authDomain: 'myapp-9f915.firebaseapp.com',
    storageBucket: 'myapp-9f915.appspot.com',
    measurementId: 'G-11G8TD76SC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVxXBR1J__w2_Tj-kXoIWwLMubjtAncL4',
    appId: '1:287249177433:android:9ff4b240d4bc14f35cca48',
    messagingSenderId: '287249177433',
    projectId: 'myapp-9f915',
    storageBucket: 'myapp-9f915.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo1R0s2LqdynyHQ0vpr1pDro7hp4uHSuo',
    appId: '1:287249177433:ios:83686c88ad4b8af45cca48',
    messagingSenderId: '287249177433',
    projectId: 'myapp-9f915',
    storageBucket: 'myapp-9f915.appspot.com',
    iosClientId: '287249177433-qqpf32k36pp619jm3c987rojvbp75adq.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo1R0s2LqdynyHQ0vpr1pDro7hp4uHSuo',
    appId: '1:287249177433:ios:0fb72151a4dcbeda5cca48',
    messagingSenderId: '287249177433',
    projectId: 'myapp-9f915',
    storageBucket: 'myapp-9f915.appspot.com',
    iosClientId: '287249177433-6qm7009147shsiijqe9av2g500ku0efn.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
